# Application constants. Do not put mutable state in this module.

GS_APP_NAME="GitStart Lite"
GS_APP_VERSION="0.1.0"
GS_APP_ID="gitstart-lite"

# Teaching limits
GS_LIMIT_COMMIT_MSG=72
GS_LIMIT_PREVIEW_ENTRIES=20
GS_LIMIT_NARROW_COLS=70
GS_LIMIT_WIDE_COLS=100

# Lesson identifiers
GS_LESSON_INIT="initialize"
GS_LESSON_COMMIT_PUSH="commit_push"
GS_LESSON_UPDATE="update_clone"
GS_LESSON_FORK="sync_fork"
GS_LESSON_DIAGNOSE="diagnose"

# Diagnostic code groups (stable IDs)
GS_CODE_BOOT_CHECKSUM="GS-BOOT-001"
GS_CODE_BOOT_DOWNLOAD="GS-BOOT-002"
GS_CODE_TERM_INPUT="GS-TERM-001"
GS_CODE_PATH_INVALID="GS-PATH-001"
GS_CODE_PATH_DANGEROUS="GS-PATH-002"
GS_CODE_GIT_MISSING="GS-GIT-001"
GS_CODE_GIT_STATE="GS-GIT-002"
GS_CODE_GIT_IDENTITY="GS-GIT-003"
GS_CODE_NET_OFFLINE="GS-NET-001"
GS_CODE_AUTH_REQUIRED="GS-AUTH-001"
GS_CODE_SAFE_STOP="GS-SAFE-001"
GS_CODE_SAFE_SECRET="GS-SAFE-002"
GS_CODE_SAFE_DIVERGED="GS-SAFE-003"
GS_CODE_SAFE_UNRELATED="GS-SAFE-004"
GS_CODE_LESSON_CMD="GS-LESSON-001"
GS_CODE_INTERNAL="GS-INTERNAL-001"

# Mode values
GS_MODE_LEARN="learn"
GS_MODE_ASSISTED="assisted"
